### ISSUE TITLE
parameters for nnet3 tdnn model

### ISSUE THREAD

**Issue by qiaopt** [BUTSpeechFIT/ASR-hybrid-decoding#1]
hi, thanks for the excellent work.
What's the recommended values of PWIP, PLMSF, PC for nnet3 tdnn or  chain tdnn model?

**Comment by kate-egorova** [comment]
hi! Sorry for the late answer. I'd recommend starting with the neutral PWIP=0, PLMSF=1, PC=0 and then adjust them to your needs and data (e.g. more OOVs - PC = -10)
